#ifndef CODE_GENERATOR_CTX_HPP
#define CODE_GENERATOR_CTX_HPP

#include <string>
#include <cstddef>
#include <unordered_map>
#include <vector>

/** 
 * @struct CodeGeneratorFunctionContext
 * @brief context of the function
*/
struct CodeGeneratorFunctionContext {
    /// function being generated by the thread
    std::string functionName{""};

    /// position of the first free general purpose register (if there is no free gp registers, stack is used) 
    size_t gpFreeRegPos{};

    /// number for next variable (-variableNum*regSize(%rbp))
    size_t variableNum{1};

    /// mapping variable name to its address (relative to rbp)
    std::unordered_map<std::string, std::string> variableMap;
    
    /// generated asm code
    std::vector<std::string> asmCode;

    /** 
     * @brief allocating general-purpose register r(8-15)
     * @returns index of the free gp register
    */
    size_t takeGpReg() noexcept {
        return ++gpFreeRegPos;
    }

    /** 
     * @brief releasing general-purpose register r(8-15)
     * @returns index of the free gp register
    */
    size_t freeGpReg() noexcept {
        return --gpFreeRegPos;
    }
};

#endif