#ifndef ASTREE_DEFS_HPP
#define ASTREE_DEFS_HPP

#include <unordered_map>
#include <string>

/*
    abstract syntax tree related definitions
*/

enum class ASTNodeType{
    PROGRAM, FUNCTION_LIST, FUNCTION, PARAMETER, BODY, VARIABLE_LIST, VARIABLE, SWITCH_BLOCK, STATEMENT, COMPOUND_STATEMENT, 
    ASSIGNMENT_STATEMENT, RETURN_STATEMENT, IF_STATEMENT, WHILE_STATEMENT, FOR_STATEMENT, DO_WHILE_STATEMENT, SWITCH_STATEMENT, 
    NUMERICAL_EXPRESSION, EXPRESSION, RELATIONAL_EXPRESSION, BINARY_EXPRESSION, FUNCTION_CALL, ARGUMENT, LITERAL, ID, CASE, DEFAULT, BREAK, PRINTF
};

extern const std::unordered_map<ASTNodeType, std::string> astNodeTypeToString;

#endif
