#ifndef CODE_GENERATOR_DEFS_HPP
#define CODE_GENERATOR_DEFS_HPP

#include <unordered_map>
#include <vector>
#include <string>

#include "../../common/intermediate-representation-tree/defs/IRTree_defs.hpp"

/// translates jump ir node types into strings
extern const std::unordered_map<IRNodeType, std::string> nodeToJMP;

/// translates jump ir node types into opposite jumps as string
extern const std::unordered_map<IRNodeType, std::string> nodeToOppJMP;

/// const vector of names of the general-purpose registers
extern const std::vector<std::string> gpRegisters;

/** 
 * @struct CodeGeneratorThreadContext
 * @brief context of the function being generated by the current thread
*/
struct CodeGeneratorThreadContext{
    /// function being generated by the thread
    std::string functionName;
    /// position of the first free general purpose register (if there is no free gp registers, stack is used) 
    size_t gpFreeRegPos;
    /// number for next variable (-variableNum*regSize(%rbp))
    size_t variableNum;
    /// mapping variable name to its address (relative to rbp)
    std::unordered_map<std::string, std::string> variableMap;
    /// generated asm code
    std::vector<std::string> asmCode;

    /** 
     * @brief initializes the thread context
     * @param funcName - name of the function
     * @returns void
    */
    void init(const std::string& funcName){
        functionName = funcName;
        gpFreeRegPos = 0;
        variableNum = 1;
    }

    /** 
     * @brief resets the thread context
     * @returns void
    */
    void reset(){
        functionName = "";
        gpFreeRegPos = 0;
        variableNum = 1;
        variableMap.clear();
        asmCode.clear();
    }

    /** 
     * @brief allocating general-purpose register r(8-15)
     * @returns index of the free gp register
    */
    size_t takeGpReg() noexcept {
        return ++gpFreeRegPos;
    }

    /** 
     * @brief releasing general-purpose register r(8-15)
     * @returns index of the free gp register
    */
    size_t freeGpReg() noexcept {
        return --gpFreeRegPos;
    }
};

#endif
