#ifndef FUNCTION_CODE_GENERATOR_HPP
#define FUNCTION_CODE_GENERATOR_HPP

#include <vector>
#include <memory>
#include <unordered_map>
#include <string>
#include <atomic>

#include "../../common/intermediate-representation-tree/IRProgram.hpp"
#include "../../common/intermediate-representation-tree/IRFunction.hpp"
#include "../defs/code_generator_defs.hpp"
#include "statement_code_generator.hpp"

/** 
 * @class FunctionCodeGenerator
 * @brief code generator specialized for the functions
*/
class FunctionCodeGenerator {
public:
    /** 
     * @brief Creates the instance of the function code generator
     * @param asmCode - reference to a map function_name:code_of_the_function
    */
    FunctionCodeGenerator(std::unordered_map<std::string, std::vector<std::string>>& asmCode);

    /** 
     * @brief gets the context of the function generated by the current thread
     * @returns reference to the context of the current thread
    */
    static CodeGeneratorThreadContext& getContext() noexcept;

    /** 
     * @brief updates flag, whether or not printf function should be generated
     * @param _prints - flag if program prints or not
     * @returns void
    */
    static void updatePrints(bool _prints) noexcept;

    /** 
     * @brief checks whether program prints or not
     * @returns true if program prints, false otherwise 
    */
    bool hasPrint() const noexcept;

    /** 
     * @brief initializes the vector holding asm code for all functions
     * @param _root - const pointer to the irt program
     * @returns void
    */
    void initFunctions(const IRProgram* _root);

    /** 
     * @brief generates the asm code of the function
     * @param _function - const pointer to the irt function
     * @returns void
    */
    void generateFunction(const IRFunction* _function);

private:
    /// thread local context of the function
    static thread_local CodeGeneratorThreadContext codeGenContext;
    /// flag whether or not program prints
    static std::atomic<bool> prints;
    /// code generator specialized for statements
    StatementCodeGenerator stmtGenerator;

    /// mutex for concurrent access to asmCode
    std::mutex asmMtx;
    /// maps functionName to its asm code
    std::unordered_map<std::string, std::vector<std::string>>& asmCode;

    /** 
     * @brief generates the parameters of the function
     * @param _parameters - reference to a const vector of pointers to the parameters
     * @returns void
    */
    void generateParameter(const std::vector<std::unique_ptr<IRParameter>>& _parameters);

};

#endif