#ifndef FUNCTION_CODE_GENERATOR_HPP
#define FUNCTION_CODE_GENERATOR_HPP

#include <vector>
#include <memory>
#include <unordered_map>
#include <string>

#include "../../common/intermediate-representation-tree/ir_program.hpp"
#include "../../common/intermediate-representation-tree/ir_function.hpp"
#include "../defs/code_generator_defs.hpp"
#include "statement_code_generator.hpp"

/** 
 * @class FunctionCodeGenerator
 * @brief code generator specialized for the functions
*/
class FunctionCodeGenerator {
public:
    /** 
     * @brief Creates the instance of the function code generator
     * @param asmCode - reference to a map function_name:code_of_the_function
    */
    FunctionCodeGenerator(std::unordered_map<std::string, std::vector<std::string>>& asmCode);

    /** 
     * @brief gets the context of the function generated by the current thread
     * @returns reference to the context of the current thread
    */
    static CodeGeneratorThreadContext& getContext() noexcept;

    /** 
     * @brief initializes the vector holding asm code for all functions
     * @param _root - const pointer to the irt program
    */
    void initFunctions(const IRProgram* _root);

    /** 
     * @brief generates the asm code of the function
     * @param _function - const pointer to the irt function
    */
    void generateFunction(const IRFunction* _function);

    /** 
     * @brief generates the parameters of the function
     * @param _parameters - reference to a const vector of pointers to the parameters
    */
    void generateParameter(const std::vector<std::unique_ptr<IRParameter>>& _parameters);

private:
    /// thread local context of the function
    static thread_local CodeGeneratorThreadContext codeGenContext;

    /// mutex for concurrent access to asmCode
    std::mutex asmMtx;

    /// code generator specialized for statements
    StatementCodeGenerator stmtGenerator;

    /// maps functionName to its asm code
    std::unordered_map<std::string, std::vector<std::string>>& asmCode;

};

#endif